### ISSUE TITLE
大佬你好，这是谁遇到了报错

### ISSUE THREAD

**Issue by Graduallyhui** [jiluoQAQ/Pokemon#1]
![1](https://github.com/jiluoQAQ/Pokemon/assets/124028234/343fe26f-7189-4012-a22b-948cc6f7b49e)
谢谢大佬的插件，在启动时遇到了 whois 出现报错。
还有一些小建议，添加设置野外探索cd或者一次探索多次合并转发，减少刷屏

**Comment by jiluoQAQ** [comment]
poetry run pip install pygtrie
安装依赖重启既可
合并转发的话因为部分平台不支持合并转发的消息，所以就没加

**Comment by Graduallyhui** [comment]
> poetry run pip install pygtrie 安装依赖重启既可 合并转发的话因为部分平台不支持合并转发的消息，所以就没加

谢谢大佬，完美解决报错了
