### ISSUE TITLE
【寻求帮助】util是哪个？

### ISSUE THREAD

**Issue by Agnes4m** [jiluoQAQ/Pokemon#10]
不是一个功能问题哈，就是学习学习（）

[chara.py](https://github.com/jiluoQAQ/Pokemon/blob/main/Pokemon/pokemon_whois/chara.py)的util并没有被识别，我也没看到导入任何相关的库，似乎萌新想请教下是什么模块QAQ
![image](https://github.com/jiluoQAQ/Pokemon/assets/70925546/bab4ee8d-5553-4e17-9de5-2990d4498ff2)

**Comment by jiluoQAQ** [comment]
这个是老的版本角色别称重定义，已经作废了，用新的方法了，这个没删掉
