### ISSUE TITLE
请问大佬，猜猜我是谁报错了

### ISSUE THREAD

**Issue by czl531** [jiluoQAQ/Pokemon#2]
![1](https://github.com/jiluoQAQ/Pokemon/assets/82907627/2c5c1793-2fb7-48ab-9261-c53f5c08f080)

**Comment by czl531** [comment]
测试发现第一次答对后，第二次发我是谁就会报错。
如果是自动超时就没事，感觉是resp的定时器还没结束就return的问题。具体不太懂

**Comment by jiluoQAQ** [comment]
更新core
