### ISSUE TITLE
赠送道具

### ISSUE THREAD

**Issue by kure29** [jiluoQAQ/Pokemon#5]
希望赠送道具能够增加使用昵称，官方bot太痛苦了

**Comment by jiluoQAQ** [comment]
[发放奖励&赠送道具添加给予对象的昵称识别](https://github.com/jiluoQAQ/Pokemon/commit/a7e062ce8034eee578d1edbc63d35371b46ee121)

**Comment by kure29** [comment]
感谢无疑大佬

**Comment by KimigaiiWuyi** [comment]
> 感谢无疑大佬

草 他是季落  😡

**Comment by KimigaiiWuyi** [comment]
> > 感谢无疑大佬
> 
> 草 什么无疑 他是季落😡
