### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Allure-Gui** [jiluoQAQ/Pokemon#6]
前往地点能匹配地区名称吗？比如前往丰缘地区。
有的萌新用户前往不了想去的地区（不熟悉地图）

**Comment by jiluoQAQ** [comment]
可以查看地图后面跟地区名称查询对应地区的地点信息去往想要去的地点。如查看地图丰缘，就可以看到丰缘地区的地点信息了，设定是只有拿到8个徽章才能前往其他地区

**Comment by jiluoQAQ** [comment]
![image](https://github.com/jiluoQAQ/Pokemon/assets/34079036/338d60f0-6b89-4451-8ed2-bb9d1f3bfdcd)
