### ISSUE TITLE
我是谁猜对后没反应

### ISSUE THREAD

**Issue by Le7emps** [jiluoQAQ/Pokemon#7]
[Raw] raw_text=热带龙, image=None, at=None, image_list=None, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=red, bot_self_id=3072536533, msg_id=7343142549979479347, user_type=group, group_id=794920410, user_id=3531135846, user_pm=6, content=[Message(type='text', data='热带龙')],
Task exception was never retrieved
future: <Task finished name='Task-15066' coro=<pokemon_whois() done, defined at E:\360MoveData\Users\DELL\Desktop\update\gsuid_core\gsuid_core\sv.py:34> exception=TypeError("'int' object is not subscriptable")>
Traceback (most recent call last):
  File "E:\360MoveData\Users\DELL\Desktop\update\gsuid_core\gsuid_core\sv.py", line 37, in wrapper
    result = await func(bot, event)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\360MoveData\Users\DELL\Desktop\update\gsuid_core\gsuid_core\plugins\Pokemon\Pokemon\pokemon_whois\__init__.py", line 255, in pokemon_whois
    myname = myname[:10]
             ~~~~~~^^^^^
TypeError: 'int' object is not subscriptable

**Comment by jiluoQAQ** [comment]
[修改纯数字昵称会导致名字缩减出错的bug](https://github.com/jiluoQAQ/Pokemon/commit/b12ccfe81a0b78a755905b30a240cecef314714a)
