### ISSUE TITLE
部分招式效果无效

### ISSUE THREAD

**Issue by Dawn-horn** [jiluoQAQ/Pokemon#8]
辅助力量：
攻击目标造成伤害。自身每有一项[能力变化]提升一级，招式威力增加20。自身的能力降低不会影响辅助力量的威力。
充电：
使自身进入充电状态。处于充电状态的宝可梦使用的[电属性]招式的威力加倍。充电状态在下次使用[电属性]招式后结束。

**Comment by jiluoQAQ** [comment]
部分技能效果没时间改，欢迎pr
