### ISSUE TITLE
彩蛋检测条件问题

### ISSUE THREAD

**Issue by Dawn-horn** [jiluoQAQ/Pokemon#9]
原文
               if pokemonid == 22 and '火' in POKEMON_LIST[mypokelist[0]][7]:
                    chongsheng_num = await POKE.get_chongsheng_num(uid,250)
                    if chongsheng_num >= 99999:
                        egg_cd_num = int(math.floor(random.uniform(0, 100)))
                        if egg_cd_num <= 50:
                            await POKE._add_pokemon_egg(uid, 250, 1)
                            mes += f'\n您获得了{CHARA_NAME[250][0]}精灵蛋x1'
                        await POKE._new_chongsheng_num(uid,250)
其中第一句检测重生的宝可梦为22号且为火属性
但22号宝可梦大嘴雀为一般&飞行属性
即重生计数永远不会增加

**Comment by jiluoQAQ** [comment]
POKEMON_LIST[mypokelist[0]][7]表示是我击败大嘴雀的那只精灵的属性，是要火属性
